module JSON
  module API
    VALIDATION_ERROR = 100
    INVALID_RESOURCE = 101
    FILTER_NOT_ALLOWED = 102
    INVALID_FILTER_VALUE = 103
    INVALID_FIELD_VALUE = 104
    INVALID_FIELD = 105
    PARAM_NOT_ALLOWED = 106

    RECORD_NOT_FOUND = 404
  end
end
