require 'jsonapi/resource'
require 'jsonapi/resources/version'
require 'jsonapi/configuration'
require 'jsonapi/paginator'
require 'jsonapi/formatter'
require 'jsonapi/routing_ext'
require 'jsonapi/mime_types'
