name: CI

on:
  push:
    branches: [ 'master', 'release-0-8', 'release-0-9', 'release-0-10' ]
  pull_request:
    branches: ['**']

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.6.6
          - 2.7.2
          - 3.0.0
        rails:
          - 6.1.3.1
          - 6.0.3.4
          - 5.2.4.4
          - 5.1.7
        database_url:
          - postgresql://postgres:password@localhost:5432/test
          - sqlite3:test_db
        exclude:
          - ruby: 3.0.0
            rails: 6.0.3.4
          - ruby: 3.0.0
            rails: 5.2.4.4
          - ruby: 3.0.0
            rails: 5.1.7
          - database_url: postgresql://postgres:password@localhost:5432/test
            rails: 5.1.7
    env:
      RAILS_VERSION: ${{ matrix.rails }}
      DATABASE_URL: ${{ matrix.database_url }}
    name: Ruby ${{ matrix.ruby }} Rails ${{ matrix.rails }} DB ${{ matrix.database_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake test